{{- if .Values.gateway.enabled }}
{{- $tlsHostname := .Values.gateway.tlsHostname -}}
{{- if and (not $tlsHostname) .Values.global.baseDomain -}}
{{- $tlsHostname = printf "opensearch.%s" .Values.global.baseDomain -}}
{{- end -}}
{{- if not $tlsHostname -}}
{{- fail "Set gateway.tlsHostname or global.baseDomain when gateway.enabled=true" -}}
{{- end -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-default
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: kgateway
  listeners:
    - name: tls
      protocol: TLS
      hostname: {{ $tlsHostname | quote }}
      tls:
        mode: Passthrough
      port: 11443
    - name: http
      protocol: HTTP
      port: 8075
      allowedRoutes:
        namespaces:
          from: All
{{- end }}
