{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: observer
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: kgateway-envoy
  hostnames:
  - observer.{{ .Values.global.baseDomain }}
  rules:
  - filters:
    backendRefs:
    - name: observer
      port: 8080
{{- end }}
