{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: observer
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: observability-gateway-default
    namespace: {{ .Release.Namespace }}
  hostnames:
  - observer.{{ .Values.global.baseDomain }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: observer
      port: 8080
{{- end }}
