apiVersion: openchoreo.dev/v1alpha1
kind: Environment
metadata:
  annotations:
    openchoreo.dev/description: Production environment for live applications.
    openchoreo.dev/display-name: Production Environment
  labels:
    openchoreo.dev/name: production
  name: production
  namespace: default
spec:
  dataPlaneRef:
    kind: DataPlane
    name: default
  gateway:
    dnsPrefix: prod
  isProduction: true
