apiVersion: openchoreo.dev/v1alpha1
kind: Environment
metadata:
  annotations:
    openchoreo.dev/description: QA environment for testing and validation.
    openchoreo.dev/display-name: QA Environment
  labels:
    openchoreo.dev/name: qa
  name: qa
  namespace: default
spec:
  dataPlaneRef:
    kind: DataPlane
    name: default
  gateway:
    dnsPrefix: qa
  isProduction: false
