apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "openchoreo-control-plane.name" . }}-validating-webhook-configuration
  labels:
    {{- include "openchoreo-control-plane.componentLabels" (dict "context" . "component" .Values.controllerManager.name) | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.controllerManager.name }}-webhook-server-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.controllerManager.name }}-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-openchoreo-dev-v1alpha1-component
  failurePolicy: Fail
  name: vcomponent-v1alpha1.kb.io
  rules:
  - apiGroups:
    - openchoreo.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - components
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.controllerManager.name }}-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-openchoreo-dev-v1alpha1-componentrelease
  failurePolicy: Fail
  name: vcomponentrelease-v1alpha1.kb.io
  rules:
  - apiGroups:
    - openchoreo.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - componentreleases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.controllerManager.name }}-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-openchoreo-dev-v1alpha1-clustercomponenttype
  failurePolicy: Fail
  name: vclustercomponenttype-v1alpha1.kb.io
  rules:
  - apiGroups:
    - openchoreo.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clustercomponenttypes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.controllerManager.name }}-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-openchoreo-dev-v1alpha1-componenttype
  failurePolicy: Fail
  name: vcomponenttype-v1alpha1.kb.io
  rules:
  - apiGroups:
    - openchoreo.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - componenttypes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.controllerManager.name }}-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-openchoreo-dev-v1alpha1-releasebinding
  failurePolicy: Fail
  name: vreleasebinding-v1alpha1.kb.io
  rules:
  - apiGroups:
    - openchoreo.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - releasebindings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.controllerManager.name }}-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /validate-openchoreo-dev-v1alpha1-trait
  failurePolicy: Fail
  name: vtrait-v1alpha1.kb.io
  rules:
  - apiGroups:
    - openchoreo.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - traits
  sideEffects: None
