{{- if .Values.openbao.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.openbao.secretStore.auth.kubernetes.serviceAccountName | default "external-secrets-openbao" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-build-plane.labels" . | nindent 4 }}
{{- end }}
