{{- if .Values.gateway.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: openchoreo-selfsigned-issuer
  labels:
    {{- include "openchoreo-data-plane.componentLabels" (dict "context" . "component" "gateway") | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
