{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-default
  namespace: {{ .Release.Namespace }}
  annotations:
{{- if or (index .Values "cert-manager" "enabled") (.Capabilities.APIVersions.Has "cert-manager.io/v1") }}
    cert-manager.io/cluster-issuer: {{ .Values.gateway.tls.clusterIssuer | default "openchoreo-selfsigned-issuer" }}
{{- end }}
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    {{- include "openchoreo-data-plane.componentLabels" (dict "context" . "component" "gateway") | nindent 4 }}
spec:
  gatewayClassName: kgateway
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.httpPort | default 80 }}
      allowedRoutes:
        namespaces:
          from: All
{{- if or (index .Values "cert-manager" "enabled") (.Capabilities.APIVersions.Has "cert-manager.io/v1") }}
    - name: https
      protocol: HTTPS
      port: {{ .Values.gateway.httpsPort | default 443 }}
      hostname: {{ .Values.gateway.tls.hostname | default "*.openchoreoapis.localhost" | quote }}
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: openchoreo-gateway-tls
            namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
