{{- if index .Values "gateway" "enabled" }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: openchoreo
  labels:
    {{- include "openchoreo-data-plane.componentLabels" (dict "context" . "component" "gateway") | nindent 4 }}
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
{{- end }}
