{{- if .Values.backstage.enabled }}
{{- if and .Values.backstage.ingress.enabled .Values.gateway.enabled -}}
{{- $host := include "openchoreo.consoleHost" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "openchoreo-control-plane.fullname" . }}-backstage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: backstage
  {{- with .Values.backstage.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: gateway-default
      namespace: {{ .Release.Namespace }}
  hostnames:
    {{- if .Values.backstage.ingress.hosts }}
    {{- range .Values.backstage.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
    {{- else }}
    - {{ $host | quote }}
    {{- end }}
  rules:
    {{- if .Values.backstage.ingress.hosts }}
    {{- range .Values.backstage.ingress.hosts }}
    {{- range .paths }}
    - matches:
        - path:
            type: {{ .pathType }}
            value: {{ .path }}
      backendRefs:
        - name: {{ include "openchoreo-control-plane.fullname" $ }}-ui
          port: {{ $.Values.backstage.service.port }}
    {{- end }}
    {{- end }}
    {{- else }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "openchoreo-control-plane.fullname" . }}-ui
          port: {{ .Values.backstage.service.port }}
    {{- end }}
{{- end }}
{{- end }}
