{{- if and .Values.backstage.enabled .Values.backstage.http.enabled .Values.gateway.enabled .Values.backstage.http.hostnames -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "openchoreo-control-plane.fullname" . }}-backstage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: backstage
  {{- with .Values.backstage.http.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: gateway-default
      namespace: {{ .Release.Namespace }}
  {{- with .Values.backstage.http.hostnames }}
  hostnames:
    {{- range . }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/openchoreo-observability-backend/chat
      timeouts:
        request: "450s"
        backendRequest: "450s"
      backendRefs:
        - name: {{ include "openchoreo-control-plane.fullname" $ }}-ui
          port: {{ .Values.backstage.service.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "openchoreo-control-plane.fullname" . }}-ui
          port: {{ .Values.backstage.service.port }}
{{- end }}
