{{- if .Values.backstage.enabled }}
{{- if .Values.backstage.priorityClass.create }}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.backstage.priorityClass.name }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: backstage
value: {{ .Values.backstage.priorityClass.value }}
globalDefault: false
description: "Priority class for Backstage UI"
{{- end }}
{{- end }}
