{{- if .Values.backstage.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openchoreo-control-plane.fullname" . }}-backstage-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: backstage
type: Opaque
data:
  backend-secret: {{ (.Values.backstage.backendSecret | default (randAlphaNum 32)) | b64enc | quote }}
  client-secret: {{ .Values.backstage.auth.clientSecret | b64enc | quote }}
  {{- if eq .Values.backstage.database.type "postgresql" }}
  postgres-password: {{ .Values.backstage.database.postgresql.password | b64enc | quote }}
  {{- end }}
{{- end }}
