{{- if .Values.backstage.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: backstage
type: Opaque
data:
  backend-secret: {{ (.Values.backstage.backendSecret | default (randAlphaNum 32)) | b64enc | quote }}
{{- end }}
