{{- if .Values.backstage.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openchoreo-control-plane.backstage.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: backstage
  {{- with .Values.backstage.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
