# permissions for end users to view componentreleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openchoreo
    app.kubernetes.io/managed-by: kustomize
  name: componentrelease-viewer-role
rules:
- apiGroups:
  - openchoreo.dev
  resources:
  - componentreleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openchoreo.dev
  resources:
  - componentreleases/status
  verbs:
  - get
