resources:
  # All RBAC will be applied under this service account in
  # the deployment namespace. You may comment out this resource
  # if your manager will use a service account that exists at
  # runtime. Be sure to update RoleBinding and ClusterRoleBinding
  # subjects if changing service account names.
  - service_account.yaml
  - role.yaml
  - role_binding.yaml
  - leader_election_role.yaml
  - leader_election_role_binding.yaml
  # The following RBAC configurations are used to protect
  # the metrics endpoint with authn/authz. These configurations
  # ensure that only authorized users and service accounts
  # can access the metrics endpoint. Comment the following
  # permissions if you want to disable this protection.
  # More info: https://book.kubebuilder.io/reference/metrics.html
  - metrics_auth_role.yaml
  - metrics_auth_role_binding.yaml
  - metrics_reader_role.yaml
  # For each CRD, "Editor" and "Viewer" roles are scaffolded by
  # default, aiding admins in cluster management. Those roles are
  # not used by the Project itself. You can comment the following lines
  # if you do not want those helpers be installed with your Project.
  - project_editor_role.yaml
  - project_viewer_role.yaml
  - namespace_editor_role.yaml
  - namespace_viewer_role.yaml
  # For each CRD, "Editor" and "Viewer" roles are scaffolded by
  # default, aiding admins in cluster management. Those roles are
  # not used by the Project itself. You can comment the following lines
  # if you do not want those helpers be installed with your Project.
  - deploymenttrack_editor_role.yaml
  - deploymenttrack_viewer_role.yaml
  - component_editor_role.yaml
  - component_viewer_role.yaml
  - componenttype_editor_role.yaml
  - componenttype_viewer_role.yaml
  - deploymentpipeline_editor_role.yaml
  - deploymentpipeline_viewer_role.yaml
  - dataplane_editor_role.yaml
  - dataplane_viewer_role.yaml
  - environment_editor_role.yaml
  - environment_viewer_role.yaml
  # For each CRD, "Editor" and "Viewer" roles are scaffolded by
  # default, aiding admins in cluster management. Those roles are
  # not used by the Project itself. You can comment the following lines
  # if you do not want those helpers be installed with your Project.
  - workload_editor_role.yaml
  - workload_viewer_role.yaml
  - configurationgroup_editor_role.yaml
  - configurationgroup_viewer_role.yaml
# For each CRD, "Editor" and "Viewer" roles are scaffolded by
# default, aiding admins in cluster management. Those roles are
# not used by the Project itself. You can comment the following lines
# if you do not want those helpers be installed with your Project.
  - releasebinding_editor_role.yaml
  - releasebinding_viewer_role.yaml
  - componentrelease_editor_role.yaml
  - componentrelease_viewer_role.yaml
  - secretreference_editor_role.yaml
  - secretreference_viewer_role.yaml
  - release_editor_role.yaml
  - release_viewer_role.yaml
  - gitcommitrequest_editor_role.yaml
  - gitcommitrequest_viewer_role.yaml
  - buildplane_admin_role.yaml
  - buildplane_editor_role.yaml
  - buildplane_viewer_role.yaml
  - build_admin_role.yaml
  - build_editor_role.yaml
  - build_viewer_role.yaml
# For each CRD, "Admin", "Editor" and "Viewer" roles are scaffolded by
# default, aiding admins in cluster management. Those roles are
# not used by the openchoreo itself. You can comment the following lines
# if you do not want those helpers be installed with your Project.
  - clustercomponenttype_admin_role.yaml
  - clustercomponenttype_editor_role.yaml
  - clustercomponenttype_viewer_role.yaml
  - authzclusterrolebinding_admin_role.yaml
  - authzclusterrolebinding_editor_role.yaml
  - authzclusterrolebinding_viewer_role.yaml
  - authzclusterrole_admin_role.yaml
  - authzclusterrole_editor_role.yaml
  - authzclusterrole_viewer_role.yaml
  - authzrolebinding_admin_role.yaml
  - authzrolebinding_editor_role.yaml
  - authzrolebinding_viewer_role.yaml
  - authzrole_admin_role.yaml
  - authzrole_editor_role.yaml
  - authzrole_viewer_role.yaml
  - clusterobservabilityplane_admin_role.yaml
  - clusterobservabilityplane_editor_role.yaml
  - clusterobservabilityplane_viewer_role.yaml
  - clusterbuildplane_admin_role.yaml
  - clusterbuildplane_editor_role.yaml
  - clusterbuildplane_viewer_role.yaml
  - clusterdataplane_admin_role.yaml
  - clusterdataplane_editor_role.yaml
  - clusterdataplane_viewer_role.yaml
  - clustertrait_admin_role.yaml
  - clustertrait_editor_role.yaml
  - clustertrait_viewer_role.yaml
  - componentworkflowrun_admin_role.yaml
  - componentworkflowrun_editor_role.yaml
  - componentworkflowrun_viewer_role.yaml
  - componentworkflow_admin_role.yaml
  - componentworkflow_editor_role.yaml
  - componentworkflow_viewer_role.yaml
  - workflow_admin_role.yaml
  - workflow_editor_role.yaml
  - workflow_viewer_role.yaml
  - workflowrun_admin_role.yaml
  - workflowrun_editor_role.yaml
  - workflowrun_viewer_role.yaml
  - observabilityplane_admin_role.yaml
  - observabilityplane_editor_role.yaml
  - observabilityplane_viewer_role.yaml
  - observabilityalertsnotificationchannel_admin_role.yaml
  - observabilityalertsnotificationchannel_editor_role.yaml
  - observabilityalertsnotificationchannel_viewer_role.yaml
  - observabilityalertrule_admin_role.yaml
  - observabilityalertrule_editor_role.yaml
  - observabilityalertrule_viewer_role.yaml

