# permissions for end users to edit releasebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openchoreo
    app.kubernetes.io/managed-by: kustomize
  name: releasebinding-editor-role
rules:
- apiGroups:
  - openchoreo.dev
  resources:
  - releasebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openchoreo.dev
  resources:
  - releasebindings/status
  verbs:
  - get
