{{- if .Values.clusterGateway.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "openchoreo-control-plane.clusterGateway.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "openchoreo-control-plane.clusterGateway.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "openchoreo-control-plane.clusterGateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
