{{- if .Values.clusterAgent.enabled }}
{{- if .Values.clusterAgent.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "openchoreo-data-plane.clusterAgent.name" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-data-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster-agent
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-4"
spec:
  secretName: {{ .Values.clusterAgent.tls.secretName }}
  commonName: {{ .Values.clusterAgent.planeName }}
  issuerRef:
    kind: Issuer
    name: {{ include "openchoreo-data-plane.clusterAgent.name" . }}-selfsigned-issuer
  {{- with .Values.clusterAgent.tls.duration }}
  duration: {{ . }}
  {{- end }}
  {{- with .Values.clusterAgent.tls.renewBefore }}
  renewBefore: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
