controllerManager:
  image:
    pullPolicy: Never

openchoreoApi:
  image:
    pullPolicy: Never
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: api.openchoreo.localhost
        paths:
          - path: /
            pathType: Prefix
            port: 8080

backstage:
  image:
    pullPolicy: Never
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: openchoreo.localhost
        paths:
          - path: /
            pathType: Prefix
            port: 7007
  baseUrl: http://openchoreo.localhost:7007
  auth:
    authorizationUrl: http://thunder.openchoreo.localhost:7007/oauth2/authorize

asgardeoThunder:
  image:
    pullPolicy: Never
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: thunder.openchoreo.localhost
        paths:
          - path: /
            pathType: Prefix
            port: 8090
