apiVersion: openchoreo.dev/v1alpha1
kind: Environment
metadata:
  name: development
  namespace: default
  annotations:
    openchoreo.dev/display-name: Development
    openchoreo.dev/description: Development
  labels:
    openchoreo.dev/name: development
spec:
  dataPlaneRef:
    kind: DataPlane
    name: default
  isProduction: false
  gateway:
    dnsPrefix: dev
---
apiVersion: openchoreo.dev/v1alpha1
kind: Environment
metadata:
  name: staging
  namespace: default
  annotations:
    openchoreo.dev/display-name: Staging
    openchoreo.dev/description: Staging
  labels:
    openchoreo.dev/name: staging
spec:
  dataPlaneRef:
    kind: DataPlane
    name: default
  isProduction: false
  gateway:
    dnsPrefix: staging
---
apiVersion: openchoreo.dev/v1alpha1
kind: Environment
metadata:
  name: production
  namespace: default
  annotations:
    openchoreo.dev/display-name: Production
    openchoreo.dev/description: Production
  labels:
    openchoreo.dev/name: production
spec:
  dataPlaneRef:
    kind: DataPlane
    name: default
  isProduction: true
  gateway:
    dnsPrefix: prod
