## Append samples of your project ##
resources:
  - openchoreo_v1alpha1_api.yaml
  - openchoreo_v1alpha1_apibinding.yaml
  - openchoreo_v1alpha1_apiclass.yaml
  - openchoreo_v1alpha1_component.yaml
  - openchoreo_v1alpha1_componenttype.yaml
  - openchoreo_v1alpha1_trait.yaml
  - openchoreo_v1alpha1_configurationgroup.yaml
  - openchoreo_v1alpha1_dataplane.yaml
  - openchoreo_v1alpha1_deployableartifact.yaml
  - openchoreo_v1alpha1_deployment.yaml
  - openchoreo_v1alpha1_deploymentpipeline.yaml
  - openchoreo_v1alpha1_deploymenttrack.yaml
  - openchoreo_v1alpha1_endpoint.yaml
  - openchoreo_v1alpha1_environment.yaml
  - openchoreo_v1alpha1_gitcommitrequest.yaml
  - openchoreo_v1alpha1_project.yaml
  - openchoreo_v1alpha1_release.yaml
  - openchoreo_v1alpha1_scheduledtask.yaml
  - openchoreo_v1alpha1_scheduledtaskbinding.yaml
  - openchoreo_v1alpha1_scheduledtaskclass.yaml
  - openchoreo_v1alpha1_service.yaml
  - openchoreo_v1alpha1_servicebinding.yaml
  - openchoreo_v1alpha1_serviceclass.yaml
  - openchoreo_v1alpha1_webapplication.yaml
  - openchoreo_v1alpha1_webapplicationbinding.yaml
  - openchoreo_v1alpha1_webapplicationclass.yaml
  - openchoreo_v1alpha1_workload.yaml
  - openchoreo_v1alpha1_build.yaml
  - openchoreo_v1alpha1_buildplane.yaml
  - openchoreo_v1alpha1_workflow.yaml
  - openchoreo_v1alpha1_workflowrun.yaml
  - openchoreo_v1alpha1_secretreference.yaml
  - openchoreo_v1alpha1_componentrelease.yaml
  - openchoreo_v1alpha1_releasebinding.yaml
  - v1alpha1_componentworkflow.yaml
  - v1alpha1_componentworkflowrun.yaml
  - openchoreo_v1alpha1_observabilityplane.yaml
  - v1alpha1_observabilityalertsnotificationchannel.yaml
  - v1alpha1_observabilityalertrule.yaml
  - v1alpha1_authzrole.yaml
  - v1alpha1_authzrolebinding.yaml
  - v1alpha1_authzclusterrole.yaml
  - v1alpha1_authzclusterrolebinding.yaml
  - openchoreo_v1alpha1_clusterdataplane.yaml
  - openchoreo_v1alpha1_clusterbuildplane.yaml
  - openchoreo_v1alpha1_clusterobservabilityplane.yaml
  - openchoreo_v1alpha1_clustercomponenttype.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
