# TODO: chathurangas: rename this file
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openchoreo.dev/display-name: Default Namespace
    openchoreo.dev/description: This is the default namespace for this setup
  labels:
    openchoreo.dev/name: default-namespace
  name: default-namespace
