apiVersion: openchoreo.dev/v1alpha1
kind: AuthzRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: openchoreo
    app.kubernetes.io/managed-by: kustomize
  name: dev-team-crm-project
  namespace: acme-org
spec:
  entitlement:
    claim: groups
    value: dev-team
  roleRef:
    kind: AuthzRole
    name: developer
  targetPath:
    project: crm
  effect: allow
