{{- if .Values.openchoreoApi.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "openchoreo-control-plane.openchoreoApi.name" . }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
rules:
- apiGroups:
  - openchoreo.dev
  resources:
  - apibindings
  - apiclasses
  - apis
  - buildplanes
  - builds
  - componentreleases
  - components
  - componenttypes
  - componentworkflows
  - componentworkflowruns
  - dataplanes
  - deployableartifacts
  - deploymentpipelines
  - deployments
  - deploymenttracks
  - endpoints
  - environments
  - gitcommitrequests
  - observabilityplanes
  - organizations
  - projects
  - releasebindings
  - releases
  - scheduledtaskbindings
  - scheduledtaskclasses
  - scheduledtasks
  - servicebindings
  - serviceclasses
  - services
  - traits
  - webapplicationbindings
  - webapplicationclasses
  - webapplications
  - workflows
  - workflowruns
  - workloads
  - secretreferences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openchoreo.dev
  resources:
  - apibindings/status
  - apiclasses/status
  - apis/status
  - buildplanes/status
  - builds/status
  - componentreleases/status
  - components/status
  - componenttypes/status
  - componentworkflows/status
  - componentworkflowruns/status
  - dataplanes/status
  - deployableartifacts/status
  - deploymentpipelines/status
  - deployments/status
  - deploymenttracks/status
  - endpoints/status
  - environments/status
  - gitcommitrequests/status
  - observabilityplanes/status
  - organizations/status
  - projects/status
  - releasebindings/status
  - releases/status
  - scheduledtaskbindings/status
  - scheduledtaskclasses/status
  - scheduledtasks/status
  - servicebindings/status
  - serviceclasses/status
  - services/status
  - traits/status
  - webapplicationbindings/status
  - webapplicationclasses/status
  - webapplications/status
  - workloads/status
  - secretreferences/status
  verbs:
  - get
  - patch
  - update
{{- end }}
