{{- if .Values.openchoreoApi.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "openchoreo-control-plane.openchoreoApi.name" . }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
rules:
- apiGroups:
  - openchoreo.dev
  resources:
  - authzclusterrolebindings
  - authzclusterroles
  - authzrolebindings
  - authzroles
  - apibindings
  - apiclasses
  - apis
  - buildplanes
  - builds
  - clusterbuildplanes
  - clustercomponenttypes
  - clusterdataplanes
  - clusterobservabilityplanes
  - componentreleases
  - components
  - componenttypes
  - componentworkflows
  - componentworkflowruns
  - dataplanes
  - deployableartifacts
  - deploymentpipelines
  - deployments
  - deploymenttracks
  - endpoints
  - environments
  - gitcommitrequests
  - gitrepositorywebhooks
  - observabilityplanes
  - projects
  - releasebindings
  - releases
  - scheduledtaskbindings
  - scheduledtaskclasses
  - scheduledtasks
  - servicebindings
  - serviceclasses
  - services
  - traits
  - webapplicationbindings
  - webapplicationclasses
  - webapplications
  - workflows
  - workflowruns
  - workloads
  - secretreferences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openchoreo.dev
  resources:
  - apibindings/status
  - apiclasses/status
  - apis/status
  - buildplanes/status
  - builds/status
  - clusterbuildplanes/status
  - clustercomponenttypes/status
  - clusterdataplanes/status
  - clusterobservabilityplanes/status
  - componentreleases/status
  - components/status
  - componenttypes/status
  - componentworkflows/status
  - componentworkflowruns/status
  - dataplanes/status
  - deployableartifacts/status
  - deploymentpipelines/status
  - deployments/status
  - deploymenttracks/status
  - endpoints/status
  - environments/status
  - gitcommitrequests/status
  - gitrepositorywebhooks/status
  - observabilityplanes/status
  - projects/status
  - releasebindings/status
  - releases/status
  - scheduledtaskbindings/status
  - scheduledtaskclasses/status
  - scheduledtasks/status
  - servicebindings/status
  - serviceclasses/status
  - services/status
  - traits/status
  - webapplicationbindings/status
  - webapplicationclasses/status
  - webapplications/status
  - workloads/status
  - secretreferences/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
{{- end }}
