{{- if and .Values.openchoreoApi.enabled .Values.openchoreoApi.ingress.enabled .Values.gateway.enabled -}}
{{- $host := include "openchoreo.apiHost" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "openchoreo-control-plane.openchoreoApi.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
  {{- with .Values.openchoreoApi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: gateway-default
      namespace: {{ .Release.Namespace }}
  hostnames:
    {{- if .Values.openchoreoApi.ingress.hosts }}
    {{- range .Values.openchoreoApi.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
    {{- else }}
    - {{ $host | quote }}
    {{- end }}
  rules:
    {{- if .Values.openchoreoApi.ingress.hosts }}
    {{- range .Values.openchoreoApi.ingress.hosts }}
    {{- range .paths }}
    - matches:
        - path:
            type: {{ .pathType }}
            value: {{ .path }}
      backendRefs:
        - name: {{ include "openchoreo-control-plane.openchoreoApi.name" $ }}
          port: 8080
    {{- end }}
    {{- end }}
    {{- else }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "openchoreo-control-plane.openchoreoApi.name" . }}
          port: 8080
    {{- end }}
{{- end }}
