{{- if and .Values.openchoreoApi.enabled .Values.openchoreoApi.ingress.enabled -}}
{{- $host := include "openchoreo.apiHost" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openchoreo-control-plane.openchoreoApi.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
  {{- with .Values.openchoreoApi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.openchoreoApi.ingress.ingressClassName | default .Values.global.ingressClassName }}
  {{- if or .Values.global.tls.enabled .Values.openchoreoApi.ingress.tls }}
  tls:
    {{- if .Values.openchoreoApi.ingress.tls }}
    {{- range .Values.openchoreoApi.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
    {{- else }}
    - hosts:
        - {{ $host | quote }}
      secretName: {{ .Values.global.tls.secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.openchoreoApi.ingress.hosts }}
    {{- range .Values.openchoreoApi.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "openchoreo-control-plane.openchoreoApi.name" $ }}
                port:
                  number: 8080
          {{- end }}
    {{- end }}
    {{- else }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "openchoreo-control-plane.openchoreoApi.name" . }}
                port:
                  number: 8080
    {{- end }}
{{- end }}
