{{- if and .Values.openchoreoApi.enabled .Values.openchoreoApi.database.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openchoreo-control-plane.openchoreoApi.name" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.openchoreoApi.database.persistence.storageClassName }}
  storageClassName: {{ .Values.openchoreoApi.database.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.openchoreoApi.database.persistence.size }}
{{- end }}
