{{- if .Values.openchoreoApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openchoreo-control-plane.openchoreoApi.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
spec:
  type: {{ .Values.openchoreoApi.service.type }}
  {{- if and (eq .Values.openchoreoApi.service.type "NodePort") .Values.openchoreoApi.service.nodePort }}
  ports:
  - port: {{ .Values.openchoreoApi.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    nodePort: {{ .Values.openchoreoApi.service.nodePort }}
  {{- else }}
  ports:
  - port: {{ .Values.openchoreoApi.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  {{- end }}
  selector:
    app.kubernetes.io/component: api-server
    {{- include "openchoreo-control-plane.selectorLabels" . | nindent 4 }}
{{- end }}
