{{- if and .Values.openchoreoApi.enabled .Values.openchoreoApi.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "openchoreo-control-plane.openchoreoApi.name" . }}
  namespace: {{ .Values.openchoreoApi.metrics.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
    {{- with .Values.openchoreoApi.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - interval: {{ .Values.openchoreoApi.metrics.serviceMonitor.interval | default "30s" }}
      path: /metrics
      port: http
      scheme: http
      {{- with .Values.openchoreoApi.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.openchoreoApi.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/component: api-server
      app.kubernetes.io/name: {{ include "openchoreo-control-plane.fullname" . }}
{{- end }}
