apiVersion: v2
name: openchoreo-data-plane
description: A Helm chart for OpenChoreo Data Plane
type: application

# Version strategy: latest-dev for development, replaced by CI for releases
version: 0.0.0-latest-dev
appVersion: "latest-dev"

home: https://github.com/openchoreo/openchoreo
icon: https://openchoreo.dev/img/openchoreo-logo.svg
sources:
  - https://github.com/openchoreo/openchoreo
keywords:
  - openchoreo
  - internal-developer-platform
  - idp
  - kubernetes
  - developer-experience
  - devops
  - platform-engineering
  - data-plane
  - gateway
  - observability
maintainers:
  - name: OpenChoreo Team
    url: https://github.com/openchoreo/openchoreo
dependencies:
  - name: fluent-bit
    repository: https://fluent.github.io/helm-charts
    version: 0.54.0
    condition: fluent-bit.enabled
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 78.3.0
    condition: kube-prometheus-stack.enabled
  - name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.140.0
    condition: opentelemetry-collector.enabled
  - name: gateway-operator
    alias: api-platform
    version: 0.2.0
    repository: oci://ghcr.io/wso2/api-platform/helm-charts
    condition: api-platform.enabled
