{{- if .Values.clusterAgent.enabled }}
{{- if .Values.clusterAgent.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openchoreo-build-plane.clusterAgent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-build-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster-agent
  {{- with .Values.clusterAgent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
