{{ if .Values.global.defaultResources.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: label-default-namespace-sa
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: label-default-namespace-role
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: label-default-namespace-rolebinding
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
subjects:
  - kind: ServiceAccount
    name: label-default-namespace-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: label-default-namespace-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}
