{{ if .Values.global.defaultResources.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-wait-sa
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller-wait-role
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-wait-rolebinding
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: controller-wait-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: controller-wait-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}
