{{- if and .Values.gateway.enabled .Values.rca.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.rca.name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: gateway-default
    sectionName: http
  hostnames:
    {{- if .Values.rca.ingress.hosts }}
    {{- range .Values.rca.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
    {{- else }}
    - {{ printf "rca-agent.%s" .Values.global.baseDomain | quote }}
    {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1/agent/chat
    backendRefs:
    - name: {{ .Values.rca.name }}
      port: {{ .Values.rca.service.port }}
    timeouts:
      request: "450s"
      backendRequest: "450s"
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1/rca-reports
    backendRefs:
    - name: {{ .Values.rca.name }}
      port: {{ .Values.rca.service.port }}
{{- end }}
