{{- if and .Values.gateway.enabled .Values.rca.enabled .Values.rca.http.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.rca.name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: gateway-default
    sectionName: http
  {{- with .Values.rca.http.hostnames }}
  hostnames:
    {{- range . }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1/agent/chat
    timeouts:
      request: "450s"
      backendRequest: "450s"
    backendRefs:
    - name: {{ .Values.rca.name }}
      port: {{ .Values.rca.service.port }}
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1/rca-reports
    backendRefs:
    - name: {{ .Values.rca.name }}
      port: {{ .Values.rca.service.port }}
{{- end }}
