{{- if .Values.rca.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openchoreo-observability-plane.fullname" . }}-rca-oauth-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-observability-plane.componentLabels" (dict "context" . "component" .Values.rca.name) | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.rca.oauth.clientSecret | b64enc | quote }}
{{- end }}
