{{- if .Values.global.defaultResources.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podman-build-cache
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: podman-build-cache
    app.kubernetes.io/component: build-cache
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.global.defaultResources.podmanCache.size }}
  {{- if .Values.global.defaultResources.podmanCache.storageClass }}
  storageClassName: {{ .Values.global.defaultResources.podmanCache.storageClass }}
  {{- end }}
{{- end }}
