{{- if .Values.controllerManager.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controllerManager.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-observability-plane.componentLabels" (dict "context" . "component" .Values.controllerManager.name) | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
{{- end }}
