apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rcaService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-observer-rca.componentLabels" (dict "context" . "component" .Values.rcaService.name) | nindent 4 }}
spec:
  type: {{ .Values.rcaService.service.type }}
  ports:
  - port: {{ .Values.rcaService.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "openchoreo-observer-rca.componentSelectorLabels" (dict "context" . "component" .Values.rcaService.name) | nindent 4 }}
