{{- if .Values.asgardeoThunder.enabled }}
{{- if .Values.asgardeoThunder.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openchoreo-control-plane.fullname" . }}-asgardeo-thunder
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: asgardeo-thunder
  annotations:
    {{- with .Values.asgardeoThunder.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.asgardeoThunder.ingress.ingressClassName | default .Values.global.ingressClassName }}
  {{- if .Values.asgardeoThunder.ingress.tls }}
  tls:
    {{- range .Values.asgardeoThunder.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.asgardeoThunder.ingress.hosts }}
    {{- range .Values.asgardeoThunder.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "openchoreo-control-plane.fullname" $ }}-asgardeo-thunder
                port:
                  number: {{ .port }}
          {{- end }}
    {{- end }}
    {{- else }}
    - host: {{ include "openchoreo.thunderHost" . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "openchoreo-control-plane.fullname" . }}-asgardeo-thunder
                port:
                  number: {{ .Values.asgardeoThunder.service.port }}
    {{- end }}
{{- end }}
{{- end }}
