{{- if .Values.asgardeoThunder.enabled }}
{{- if .Values.asgardeoThunder.persistence.database.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openchoreo-control-plane.fullname" . }}-asgardeo-thunder-database
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: asgardeo-thunder
spec:
  accessModes:
    - {{ .Values.asgardeoThunder.persistence.database.accessMode }}
  storageClassName: {{ .Values.asgardeoThunder.persistence.database.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.asgardeoThunder.persistence.database.size }}
{{- end }}
{{- end }}
