apiVersion: v2
name: openchoreo-control-plane
description: A Helm chart for OpenChoreo Control Plane
type: application

# Version strategy: latest-dev for development, replaced by CI for releases
version: 0.0.0-latest-dev
appVersion: "latest-dev"

home: https://github.com/openchoreo/openchoreo
icon: https://openchoreo.dev/img/openchoreo-logo.svg
sources:
  - https://github.com/openchoreo/openchoreo
keywords:
  - openchoreo
  - internal-developer-platform
  - idp
  - kubernetes
  - developer-experience
  - devops
  - platform-engineering
maintainers:
  - name: OpenChoreo Team
    url: https://github.com/openchoreo/openchoreo

dependencies:
  - name: traefik
    repository: https://traefik.github.io/charts
    condition: traefik.enabled
    version: "34.4.1"
  - name: thunder
    condition: thunder.enabled
    repository: oci://ghcr.io/asgardeo/helm-charts
    version: "0.14.0"
