{{- if and .Values.gateway.enabled .Values.openSearchCluster.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: opensearch
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: kgateway-envoy
  hostnames:
  - opensearch.{{ .Values.global.baseDomain }}
  rules:
  - filters:
    - type: URLRewrite
      urlRewrite:
        hostname: "opensearch"
    backendRefs:
    - name: opensearch
      port: 9200
{{- end }}
