{{- if .Values.vault.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-wait-sa
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-build-plane.labels" . | nindent 4 }}
{{- end }}