{{- if .Values.vault.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-wait-rolebinding
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-build-plane.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: vault-wait-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: vault-wait-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}