{{- if .Values.vault.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-wait-role
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-build-plane.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
{{- end }}