# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - bases/openchoreo.dev_projects.yaml
  - bases/openchoreo.dev_environments.yaml
  - bases/openchoreo.dev_dataplanes.yaml
  - bases/openchoreo.dev_deploymentpipelines.yaml
  - bases/openchoreo.dev_components.yaml
  - bases/openchoreo.dev_componenttypes.yaml
  - bases/openchoreo.dev_traits.yaml
  - bases/openchoreo.dev_deploymenttracks.yaml
  - bases/openchoreo.dev_configurationgroups.yaml
  - bases/openchoreo.dev_workloads.yaml
  - bases/openchoreo.dev_gitcommitrequests.yaml
  - bases/openchoreo.dev_releases.yaml
  - bases/openchoreo.dev_builds.yaml
  - bases/openchoreo.dev_buildplanes.yaml
  - bases/openchoreo.dev_workflows.yaml
  - bases/openchoreo.dev_workflowruns.yaml
  - bases/openchoreo.dev_secretreferences.yaml
  - bases/openchoreo.dev_componentreleases.yaml
  - bases/openchoreo.dev_releasebindings.yaml
  - bases/openchoreo.dev_observabilityplanes.yaml
  - bases/openchoreo.dev_observabilityalertsnotificationchannels.yaml
  - bases/openchoreo.dev_observabilityalertrules.yaml
  - bases/openchoreo.dev_authzroles.yaml
  - bases/openchoreo.dev_authzrolebindings.yaml
  - bases/openchoreo.dev_authzclusterroles.yaml
  - bases/openchoreo.dev_authzclusterrolebindings.yaml
  - bases/openchoreo.dev_clusterbuildplanes.yaml
  - bases/openchoreo.dev_clusterdataplanes.yaml
  - bases/openchoreo.dev_clusterobservabilityplanes.yaml
  - bases/openchoreo.dev_clustercomponenttypes.yaml
  - bases/openchoreo.dev_clustertraits.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
