{{- if .Values.thunder.enabled }}
{{- if and .Values.thunder.http.enabled .Values.gateway.enabled .Values.thunder.http.hostnames -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "openchoreo-control-plane.thunder.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: thunder
  {{- with .Values.thunder.http.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: gateway-default
      namespace: {{ .Release.Namespace }}
  {{- with .Values.thunder.http.hostnames }}
  hostnames:
    {{- range . }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "openchoreo-control-plane.thunder.name" . }}
          port: {{ .Values.thunder.service.port }}
{{- end }}
{{- end }}
