{{- if .Values.thunder.enabled }}
{{- if and .Values.thunder.ocIngress.enabled .Values.gateway.enabled -}}
{{- $host := include "openchoreo.thunderHost" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.thunder.fullnameOverride }}-openchoreo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: thunder
  {{- with .Values.thunder.ocIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: gateway-default
      namespace: {{ .Release.Namespace }}
  hostnames:
    {{- if .Values.thunder.ocIngress.hosts }}
    {{- range .Values.thunder.ocIngress.hosts }}
    - {{ .host | quote }}
    {{- end }}
    {{- else }}
    - {{ $host | quote }}
    {{- end }}
  rules:
    {{- if .Values.thunder.ocIngress.hosts }}
    {{- range .Values.thunder.ocIngress.hosts }}
    {{- range .paths }}
    - matches:
        - path:
            type: {{ .pathType }}
            value: {{ .path }}
      backendRefs:
        - name: {{ $.Values.thunder.fullnameOverride }}-service
          port: {{ .port }}
    {{- end }}
    {{- end }}
    {{- else }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.thunder.fullnameOverride }}-service
          port: {{ .Values.thunder.service.port }}
    {{- end }}
{{- end }}
{{- end }}
