{{- if .Values.thunder.enabled }}
{{- if .Values.thunder.ocIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.thunder.fullnameOverride }}-openchoreo-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: thunder
  annotations:
    {{- with .Values.thunder.ocIngress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.thunder.ocIngress.ingressClassName | default .Values.global.ingressClassName }}
  {{- if .Values.thunder.ocIngress.tls }}
  tls:
    {{- range .Values.thunder.ocIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
    {{- else }}
    - hosts:
        - {{ $host | quote }}
      secretName: {{ .Values.global.tls.secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.thunder.ocIngress.hosts }}
    {{- range .Values.thunder.ocIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .Values.thunder.fullnameOverride }}-service
                port:
                  number: {{ .port }}
          {{- end }}
    {{- end }}
    {{- else }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.thunder.fullnameOverride }}-service
                port:
                  number: {{ .Values.thunder.service.port }}
    {{- end }}
{{- end }}
{{- end }}
