{{- if and .Values.gateway.enabled .Values.gateway.envoy.mountTmpVolume }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-patcher-sa
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "9"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gateway-patcher-role
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "9"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "patch" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments/status" ]
    verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-patcher-rolebinding
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "9"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: gateway-patcher-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: gateway-patcher-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
