apiVersion: v2
name: openchoreo-observability-plane
description: A Helm chart for OpenChoreo Observability Plane
type: application

# Version strategy: latest-dev for development, replaced by CI for releases
version: 0.0.0-latest-dev
appVersion: "latest-dev"

home: https://github.com/openchoreo/openchoreo
icon: https://openchoreo.dev/img/openchoreo-logo.svg
sources:
  - https://github.com/openchoreo/openchoreo
keywords:
  - openchoreo
  - internal-developer-platform
  - idp
  - kubernetes
  - observability
  - logging
  - monitoring
  - opensearch
  - developer-experience
  - devops
  - platform-engineering
maintainers:
  - name: OpenChoreo Team
    url: https://github.com/openchoreo/openchoreo

dependencies:
  - name: kube-prometheus-stack
    version: 76.0.0
    repository: https://prometheus-community.github.io/helm-charts
    alias: prometheus
