apiVersion: v2
name: openchoreo-observability-plane
description: A Helm chart for OpenChoreo Observability Plane
type: application

# Version strategy: latest-dev for development, replaced by CI for releases
version: 0.0.0-latest-dev
appVersion: "latest-dev"

home: https://github.com/openchoreo/openchoreo
icon: https://openchoreo.dev/img/openchoreo-logo.svg
sources:
  - https://github.com/openchoreo/openchoreo
keywords:
  - openchoreo
  - internal-developer-platform
  - idp
  - kubernetes
  - observability
  - logging
  - monitoring
  - opensearch
  - developer-experience
  - devops
  - platform-engineering
maintainers:
  - name: OpenChoreo Team
    url: https://github.com/openchoreo/openchoreo

dependencies:
  - name: data-prepper
    repository: https://opensearch-project.github.io/helm-charts/
    version: 0.3.1
    condition: data-prepper.enabled
  - name: fluent-bit
    repository: https://fluent.github.io/helm-charts
    version: 0.54.0
    condition: fluent-bit.enabled
  - name: kgateway
    repository: "oci://cr.kgateway.dev/kgateway-dev/charts"
    version: v2.1.2
    condition: kgateway.enabled
  - name: kube-prometheus-stack
    alias: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 78.3.0
    condition: prometheus.enabled
  - name: opensearch
    alias: openSearch
    repository: https://opensearch-project.github.io/helm-charts/
    version: 3.3.0
    condition: openSearch.enabled
  - name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.140.0
    condition: opentelemetry-collector.enabled
  - name: opensearch-dashboards
    alias: openSearchDashboards
    repository: https://opensearch-project.github.io/helm-charts/
    version: 3.3.0
    condition: openSearchDashboards.enabled
