apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-backstage.labels" . | nindent 4 }}
type: Opaque
data:
  backend-secret: {{ (.Values.backendSecret | default (randAlphaNum 32)) | b64enc | quote }}
---

