apiVersion: v2
name: openchoreo-build-plane
description: A Helm chart for OpenChoreo Build Plane
type: application

# Version strategy: latest-dev for development, replaced by CI for releases
version: 0.0.0-latest-dev
appVersion: "latest-dev"

home: https://github.com/openchoreo/openchoreo
icon: https://openchoreo.dev/img/openchoreo-logo.svg
sources:
  - https://github.com/openchoreo/openchoreo
keywords:
  - openchoreo
  - internal-developer-platform
  - idp
  - kubernetes
  - build-automation
  - ci-cd
  - argo-workflows
  - devops
maintainers:
  - name: OpenChoreo Team
    url: https://github.com/openchoreo/openchoreo
dependencies:
  - name: argo-workflows
    repository: "https://argoproj.github.io/argo-helm"
    version: 0.45.2
  - name: fluent-bit
    repository: https://fluent.github.io/helm-charts
    version: 0.54.0
    condition: fluent-bit.enabled
  - name: openbao
    version: 0.4.0
    repository: "https://openbao.github.io/openbao-helm"
    condition: openbao.enabled
