name: OpenSSF Scorecard

on:
  # For Branch-Protection check. Only the default branch is supported.
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
  branch_protection_rule:
  # To guarantee Maintained check is occasionally updated.
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#maintained
  schedule:
    # Run weekly on Sunday 20:00 UTC (Monday 01:30 IST)
    - cron: "0 20 * * 0"
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  analysis:
    name: Scorecard Analysis
    runs-on: ubuntu-latest
    permissions:
      # Required to upload results to code-scanning dashboard
      security-events: write
      # Required to publish results and get a badge
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@99c09fe975337306107572b4fdf4db224cf8e2f2 # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload Scorecard artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: scorecard-results
          path: results.sarif
          retention-days: 5

      - name: Upload to code-scanning dashboard
        uses: github/codeql-action/upload-sarif@ab28d5ce09b08e4700b2296d39d684a7ac71d1e7 # v4
        with:
          sarif_file: results.sarif
